.TH gproto.tmac 7 2023-12-26
.rn In_Main_Source 1
.mso gproto.tmac
.so gproto.7.d/prototypes.7
.SH NAME
.B gproto.tmac
\- Groff macros to style and format arguments for man pages
.SH SYNOPSIS
.PP
.B .mso gproto.tmac
.PP
.gp_cli_prototype
.PP
.gp_cdef_start
.gp_cdef_arg
.gp_cdef_end
.gp_cdef_end_stacked
.gp_cdef_voidfunc
.SH DESCRIPTION
.PP
These macros help create consistently styles and helpfully formatted
command usage and function prototypes for the Synopsis section of a
man page.
.
.so gproto.7.d/desc_cli_prototype.7
.
.so gproto.7.d/desc_cdefs.7
.so gproto.7.d/desc_cdef_start.7
.so gproto.7.d/desc_cdef_arg.7
.so gproto.7.d/desc_cdef_end.7
.so gproto.7.d/desc_cdef_end_stacked.7
.so gproto.7.d/desc_cdef_voidfunc.7
.
.so gproto.7.d/examples.7

